import type { Metadata } from "next";
import { Fira_Mono, Share_Tech_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const shareTechMono = Share_Tech_Mono({
  variable: "--font-share-tech-mono",
  subsets: ["latin"],
  weight: ["400"],
});

const firaMono = Fira_Mono({
  variable: "--font-fira-mono",
  subsets: ["latin","cyrillic"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${shareTechMono.variable} ${firaMono.variable} antialiased min-h-screen flex flex-col items-center justify-between`}>
        <Header />
          <main className="flex flex-1 w-full max-w-7xl 
              flex-col items-center justify-between mx-auto 
              py-32 px-16 bg-white dark:bg-black sm:items-start"
          >
            {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
